### ISSUE TITLE
매칭오류

### ISSUE THREAD

**Issue by kimjunsung04** [ArpaAP/iNdirect#4]
1,2번 사람이 이 매칭되어서 대화중일때
3번사람이 매칭을 시도하면 아래와같은 오류가 발생합니다!
확인후 수정 부탁드립니다!
![image](https://user-images.githubusercontent.com/70435510/107383847-bdb29180-6b34-11eb-95d1-79c593fb9fdf.png)

**Comment by ArpaAP** [comment]
저희도 해당 문제를 어제 확인한 바 있으나 원인을 파악하고 있습니다.
임시조치로 utils/rchatmgr.py 의 MatchItem 클래스의 \__eq__ 메서드에서 다음과 같이 수정해주세요.

def \__eq__(self, other):
    try:
        return self.uid == other.uid
    except:
        return self.uid == other

이렇게 수정시 정상 작동을 확인했습니다. 최대한 빠르게 해결해보겠습니다.

**Comment by ArpaAP** [comment]
모바일에서 마크다운 적용이 어려워 평문으로 했습니다 ㅠ

**Comment by kimjunsung04** [comment]
> 저희도 해당 문제를 어제 확인한 바 있으나 원인을 파악하고 있습니다.
> 임시조치로 utils/rchatmgr.py 의 MatchItem 클래스의 __eq__ 메서드에서 다음과 같이 수정해주세요.
> 
> def __eq__(self, other):
> try:
> return self.uid == other.uid
> except:
> return self.uid == other
> 
> 이렇게 수정시 정상 작동을 확인했습니다. 최대한 빠르게 해결해보겠습니다.

빠른피드백 감사합니다!

**Comment by ArpaAP** [comment]
https://github.com/ArpaAP/iNdirect/commit/bad6bf24fc829b7f4104bb14843b3b2505994357 에서 해결 완료되었습니다.
