### ISSUE TITLE
중복매칭 오류

### ISSUE THREAD

**Issue by kimjunsung04** [ArpaAP/iNdirect#5]
3명에서 1:1 매칭을 동시에 돌리면 3명이 같이 잡힙니다.
2명방인데도 3명이 잡히는 문제입니다!
자세한건 영상을 참고해주세요!

https://user-images.githubusercontent.com/70435510/107391280-e25e3780-6b3b-11eb-9f42-31274911db10.mp4

**Comment by ArpaAP** [comment]
매칭 코드 분석 결과 utils/rchatmgr.py 86라인에서, 대기열에서 랜덤의 사람을 뽑게 되어있습니다만 매칭이 완료되어도 이 사람만 큐에서 제거되지 않아 발생하는 오류로 추정됩니다.

내일 테스트를 거쳐 실제 원인이 맞는지 파악한 후 커밋하겠습니다.
많은 관심과 기여에 감사드립니다.

**Comment by kimjunsung04** [comment]
> 매칭 코드 분석 결과 utils/rchatmgr.py 86라인에서, 대기열에서 랜덤의 사람을 뽑게 되어있습니다만 매칭이 완료되어도 이 사람만 큐에서 제거되지 않아 발생하는 오류로 추정됩니다.
> 
> 내일 테스트를 거쳐 실제 원인이 맞는지 파악한 후 커밋하겠습니다.
> 많은 관심과 기여에 감사드립니다!

감사합니다!

**Comment by ArpaAP** [comment]
https://github.com/ArpaAP/iNdirect/commit/bad6bf24fc829b7f4104bb14843b3b2505994357 에서 해결되었습니다!
